Allow ALEC plugin to be downloaded from GitHub and use by default
ALEC v1.1.1 doesn't seem to work with Horizon 30 and there isn't
currently a Docker image for ALEC v2.0.0, so download from GitHub
by default (at least for now).

Don't try to use the Docker image if alecImage isn't specified.
If the Docker image is used or an ALEC image is included in the
OpenNMS container, onms-core-init.sh already skips trying to
download from GitHub.

Remove enabled_alec from the helm-*.yaml files because it was set
to the same value as the default in opennms/values.yaml.

Without these changes, ALEC v1.1.1 would fail to initialize in the
OpenNMS container with Horizon 30:

org.apache.felix.resolver.reason.ReasonException: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=alec-opennms-standalone; type=karaf.feature; version="[0,0.0.0]"; filter:="(&(osgi.identity=alec-opennms-standalone)(type=karaf.feature)(version>=0.0.0)(version<=0.0.0))" [caused by: Unable to resolve alec-opennms-standalone/0.0.0: missing requirement [alec-opennms-standalone/0.0.0] osgi.identity; osgi.identity=alec-driver-main; type=karaf.feature [caused by: Unable to resolve alec-driver-main/1.1.1: missing requirement [alec-driver-main/1.1.1] osgi.identity; osgi.identity=org.opennms.alec.driver.main; type=osgi.bundle; version="[1.1.1,1.1.1]"; resolution:=mandatory [caused by: Unable to resolve org.opennms.alec.driver.main/1.1.1: missing requirement [org.opennms.alec.driver.main/1.1.1] osgi.wiring.package; filter:="(&(osgi.wiring.package=org.opennms.integration.api.v1.health)(version>=0.3.0)(!(version>=1.0.0)))"]]]
	at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1341)
	at org.apache.felix.resolver.ResolverImpl.doResolve(ResolverImpl.java:433)
	at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:420)
	at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:374)
	at org.apache.karaf.features.internal.region.SubsystemResolver.resolve(SubsystemResolver.java:257)
	at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:399)
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1069)
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.lambda$doProvisionInThread$13(FeaturesServiceImpl.java:1004)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.apache.felix.resolver.reason.ReasonException: Unable to resolve alec-opennms-standalone/0.0.0: missing requirement [alec-opennms-standalone/0.0.0] osgi.identity; osgi.identity=alec-driver-main; type=karaf.feature [caused by: Unable to resolve alec-driver-main/1.1.1: missing requirement [alec-driver-main/1.1.1] osgi.identity; osgi.identity=org.opennms.alec.driver.main; type=osgi.bundle; version="[1.1.1,1.1.1]"; resolution:=mandatory [caused by: Unable to resolve org.opennms.alec.driver.main/1.1.1: missing requirement [org.opennms.alec.driver.main/1.1.1] osgi.wiring.package; filter:="(&(osgi.wiring.package=org.opennms.integration.api.v1.health)(version>=0.3.0)(!(version>=1.0.0)))"]]
	at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1341)
	... 12 more
Caused by: org.apache.felix.resolver.reason.ReasonException: Unable to resolve alec-driver-main/1.1.1: missing requirement [alec-driver-main/1.1.1] osgi.identity; osgi.identity=org.opennms.alec.driver.main; type=osgi.bundle; version="[1.1.1,1.1.1]"; resolution:=mandatory [caused by: Unable to resolve org.opennms.alec.driver.main/1.1.1: missing requirement [org.opennms.alec.driver.main/1.1.1] osgi.wiring.package; filter:="(&(osgi.wiring.package=org.opennms.integration.api.v1.health)(version>=0.3.0)(!(version>=1.0.0)))"]
	at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1341)
	... 13 more
Caused by: org.apache.felix.resolver.reason.ReasonException: Unable to resolve org.opennms.alec.driver.main/1.1.1: missing requirement [org.opennms.alec.driver.main/1.1.1] osgi.wiring.package; filter:="(&(osgi.wiring.package=org.opennms.integration.api.v1.health)(version>=0.3.0)(!(version>=1.0.0)))"
	at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1341)
	... 14 more